name: Bug Report
description: File a bug report
title: "[Bug]: <title>"
labels: [bug]
body:
  - type: markdown
    attributes:
        value: |
          Thank you for submitting a bug report. Please search if your issue [already exists](https://github.com/MelvorIdle/melvoridle.github.io/labels/bug) before submitting a report.
          > [!IMPORTANT]
          > If you are using mods, please disable them and try to reproduce the issue without mods before submitting a report
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: false
  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: A clear and concise description of what you expected to happen
    validations:
      required: false
  - type: input
    id: savestring
    attributes:
      label: Save Link - Required if issue occurs with a save
      description: (IMPORTANT) If the issue occurs with one of your saves, please provide a save link for the character on which the bug is occuring. If you are unsure how to do this, please follow [these instructions](https://github.com/MelvorIdle/melvoridle.github.io/wiki/How-to-Create-a-Save-Link).
      placeholder: https://melvoridle.com/save/xxx
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Console output
      description: If you are using the game on a desktop browser, please open the console by pressing F12 and copy its contents here.
    validations:
      required: false
  - type: checkboxes
    id: platform
    attributes:
      label: Which platforms are you experiencing this bug on?
      description: Please select all that are applicable.
      options:
        - label: Chrome
        - label: Firefox
        - label: Edge
        - label: Safari
        - label: Steam
        - label: Steam (Offline Beta)
        - label: Epic Games
        - label: Mobile App (iOS)
        - label: Mobile App (Android)
        - label: Mobile App (Android Beta)
        - label: Other (Please Specify)
    validations:
      required: true
  - type: checkboxes
    id: entitlements
    attributes:
      label: Which expansions are purchased and active at the time of the bug?
      description: Please select all that are applicable.
      options:
        - label: Throne of the Herald
        - label: Atlas of Discovery
        - label: Into the Abyss
    validations:
      required: false
  - type: dropdown
    id: version
    attributes:
      label: Which version of the game are you experiencing this bug on?
      options:
        - v1.3.1
        - v1.3
    validations:
      required: true
  - type: input
    id: subversion
    attributes:
      label: Game Subversion
      description: |
        This is the version that appears in brackets next to the game version in the sidebar or character select screen. 
        ![Subversion Example Sidebar Image](https://raw.githubusercontent.com/MelvorIdle/melvoridle.github.io/master/images/subversionExample.png)![Subversion Example Character Select Image](https://raw.githubusercontent.com/MelvorIdle/melvoridle.github.io/master/images/subversionExample2.png)![Subversion Example Character Select Image](https://raw.githubusercontent.com/MelvorIdle/melvoridle.github.io/master/images/subversionExample3.png)
      placeholder: "?11181"
    validations:
      required: true
  - type: dropdown
    id: scripts
    attributes:
      label: Are you using any mods?
      description: Please let us know if you were using any mods at the time the bug occured.
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true
