name: Bug Report
description: File a bug report
title: "[Bug]: <title>"
labels: [bug]
body:
  - type: markdown
    attributes:
        value: |
          Thank you for submitting a bug report. Please search if your issue already exists before submitting a report.
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: false
  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: A clear and concise description of what you expected to happen
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Console output
      description: If you are using the game on a desktop browser, please open the console by pressing F12 and copy its contents here.
    validations:
      required: false
  - type: checkboxes
    id: platform
    attributes:
      label: Which platforms are you experiencing this bug on?
      description: Please select all that are applicable.
      options:
        - label: Chrome
        - label: Firefox
        - label: Edge
        - label: Safari
        - label: Mobile App (iOS)
        - label: Mobile App (Android)
        - label: Steam
        - label: Other (Please Specify)
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Which version of the game are you experiencing this bug on?
      options:
        - Alpha v0.21
    validations:
      required: true
  - type: input
    id: subversion
    attributes:
      label: Game Subversion
      description: |
        This is the version that appears in brackets next to the game version in the sidebar. ![Subversion Example Image](/images/subversion.png)
      placeholder: "1109"
    validations:
      required: true
  - type: dropdown
    id: scripts
    attributes:
      label: Are you using any scripts or extensions?
      description: Please let us know if you were using any scripts or browser extensions that modify the game at the time the bug occured.
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true
