name: close-empty-issues
on:
  issues:
    types: [opened]
jobs:
  close-empty:
    runs-on: ubuntu-latest
    if: github.event.issue.labels[0] == null
    steps:
      - name: Create comment
        uses: actions-cool/issues-helper@v2.4.0
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            This issue has been automatically closed due to not using one of the available issue templates. Please select one of the [available templates](https://github.com/MelvorIdle/melvoridle.github.io/issues/new/choose) and resubmit your issue.
            
            If this has been done in error due to accidently removing the label from the issue, please add the appropriate label and re-open the issue.
      - name: Close issue
        uses: actions-cool/issues-helper@v2.4.0
        with:
          actions: 'close-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
